# configuration file for dotnet-releaser
[msbuild]
project = "mouse_noise_move.csproj"
[github]
user = "PenguinCabinet"
repo = "mouse-noise-move"
[[pack]]
publish = false
rid = ["osx-arm64","osx-x64"]
kinds = []
[msbuild.properties]
IncludeAllContentForSelfExtract=false
PublishSingleFile=false