# configuration file for dotnet-releaser
[msbuild]
project = "mouse_noise_move.csproj"
[github]
user = "PenguinCabinet"
repo = "mouse-noise-move"
[[pack]]
publish = true
rid = ["osx-arm64","osx-x64"]
kinds = []
[msbuild.properties]
IncludeAllContentForSelfExtract=false
PublishSingleFile=true
[nuget]
publish = false
[brew]
publish = false