# configuration file for dotnet-releaser
[msbuild]
project = "mouse_noise_move.csproj"
[github]
user = "PenguinCabinet"
repo = "mouse-noise-move"
[[pack]]
publish = false
rid = ["win-x64"]
kinds = ["zip"]
[msbuild.properties]
IncludeAllContentForSelfExtract=false
PublishSingleFile=false